### ISSUE TITLE
Type hints seem broken since December versions

### ISSUE THREAD

**Issue by tim-hutchinson** [gtsystem/lightkube-models#8]
I started using this on a new project and wasn't getting any type hinting for any Resource/Model arguments. After poking around and trying in different IDEs, what seems to be the cause is the new `schema.py` method for importing `dataclass`. I tested by just changing the import in the model definition to be directly from `dataclasses` and type hinting immediately started working again.

I also tested by rolling back to the latest models version I could see before that change went in, which is `lightkube-models==1.28.1.4`. There, type hints work out of the box as expected.

On 1.28.1.4:
![image](https://github.com/gtsystem/lightkube-models/assets/14815358/074182b0-241a-4706-86b0-aed81b7a905b)

On 1.28.1.6:
![image](https://github.com/gtsystem/lightkube-models/assets/14815358/fd3f5026-b310-4848-9db4-11de0a17aecf)

**Comment by gtsystem** [comment]
Hi, thanks for bring up this issue. I released a new version of the models ending with `.7` (in your case `lightkube-models==1.28.1.7` and also `lightkube==0.15.1`.
I'm not sure what IDE you are using, but hopefully this should fix the issue in both pycharm and vscode.

Can you verify?

**Comment by tim-hutchinson** [comment]
Using VSCode, it's different, but not the full typing I'd expect, it now just shows args/kwargs:

<img width="666" alt="image" src="https://github.com/gtsystem/lightkube-models/assets/14815358/36961856-cb9f-4468-9314-68e3020f0fad">

**Comment by gtsystem** [comment]
Odd, with the version indicated above it works perfectly for me:

```bash
$ pip freeze | grep lightkube
lightkube==0.15.1
lightkube-models==1.28.1.7
```

VSCode:

<img width="651" alt="Screen Shot 2024-02-06 at 19 39 08" src="https://github.com/gtsystem/lightkube-models/assets/12676820/881e013a-e9e7-4fa5-8108-f642ff9db42d">

PyCharm:
<img width="1161" alt="Screen Shot 2024-02-06 at 19 42 02" src="https://github.com/gtsystem/lightkube-models/assets/12676820/a233c59d-e11b-46ff-823f-c0052d8b178e">

can you double check your environment?

**Comment by tim-hutchinson** [comment]
Ah I see, it also requires updating to lightkube `0.15.1`, not just the models, I missed that in the earlier post.

After that update it works.
